syntax = "proto3";

option java_package = "edu.eci.arsw.evolucion.eciciencia";
option java_outer_classname = "StudentProto";
option java_multiple_files = true;

service StudentService {
  rpc GetStudent       (GetStudentRequest) returns (StudentResponse);
  rpc RegisterStudent  (RegisterRequest)   returns (RegisterResponse);
}

message GetStudentRequest {
  string student_id = 1;
}

message StudentResponse {
  string student_id = 1;
  string name       = 2;
  string email      = 3;
  string major      = 4;
  bool   found      = 5;
}

message RegisterRequest {
  string name  = 1;
  string email = 2;
  string major = 3;
}

message RegisterResponse {
  string student_id = 1;
  string message    = 2;
  bool   success    = 3;
}
